### ISSUE TITLE
[FEAT]: SSR support

### ISSUE THREAD

**Issue by SteelAlloy** [shinokada/srit#1]
### Description

When using SRIT with SvelteKit I get the following error :
```
Error: <Srit> is not a valid SSR component. You may need to review your build config to ensure that dependencies are compiled, rather than imported as pre-compiled modules. Otherwise you may need to fix a <Srit>
```

Would be awesome if the markup could be generated server side !

**Comment by shinokada** [comment]
Can you show your repo?

**Comment by SteelAlloy** [comment]
Here you go

https://github.com/oganexon/srit-sandbox

**Comment by shinokada** [comment]
You have two issues:

1. You need to use `{ Srit }`.

```
<script lang="ts">
    import {Srit} from "srit";

    import imageSrc from "./images/img.jpg";

    const imageSizes = [100, 200, 400, 800];
    const imageAlt = "Test Image";
</script>

<Srit src={imageSrc} sizes={imageSizes} alt={imageAlt} />
```

2. You need to add image in the static/image directory.

Once you move all your images to static/images then code should be like this:

```
<script lang="ts">
    import {Srit} from "srit";
    const imageSizes = [100, 200, 400, 800];
    const imageSrc ='images/img.jog'
    const imageAlt = "Test Image";
</script>

<Srit src={imageSrc} sizes={imageSizes} alt={imageAlt} />
```

All your image must be in the static dir.

**Comment by SteelAlloy** [comment]
This snippet if from the README (`Srit` is imported as default value)
```html
<script lang="ts">
  import Srit from 'srit';

  const imageSrc = 'images/test-image.jpg';
  const imageSizes = [100, 200, 400, 800];
  const imageAlt = 'Test Image';
</script>
```

Anyway, I fixed those two issues 👍 
But I have now this error :
```
ReferenceError: Image is not defined
    at eval (/node_modules/srit/dist/Srit.svelte:23:16)
    at new Promise (<anonymous>)
    at getAspectRatioFromSrc (/node_modules/srit/dist/Srit.svelte:22:9)
    at eval (/node_modules/srit/dist/Srit.svelte:55:2)
    at Object.$$render (/node_modules/svelte/internal/index.mjs:1894:22)
    at eval (/src/routes/+page.svelte:15:89)
    at Object.$$render (/node_modules/svelte/internal/index.mjs:1894:22)
    at Object.default (/.svelte-kit/generated/root.svelte:74:138)
    at eval (/node_modules/@sveltejs/kit/src/runtime/components/layout.svelte:8:41)
    at Object.$$render (/node_modules/svelte/internal/index.mjs:1894:22)
```
Sadly the Image object is not defined server side

**Comment by shinokada** [comment]
Can you update your repo to see your code?

**Comment by SteelAlloy** [comment]
done

**Comment by shinokada** [comment]
Thanks. Please update to the latest version and let me know.

```
pnpm I -D srit@latest
```

**Comment by SteelAlloy** [comment]
Works now. Awesome !
